import { buildTree, type CollatzTree } from "../collatz";
import { layoutFor, type LayoutMode } from "./layout";

export interface InpOptions {
  maxSeed: number;
  flowUnits: "CFS" | "LPS" | "CMS";
  baseInvert: number;
  invertDrop: number; // per depth step toward outfall
  maxDepth: number;
  conduitLength: number;
  roughness: number;
  diameter: number;
  layoutMode: LayoutMode;
  dwfBaseflow: number; // user-defined DWF average flow at each junction
  dwfPattern: string;  // optional pattern name ("" = none)
  endTimeSec: number;  // simulation duration in seconds (min 12 h = 43200)
  peakInflow: number;  // peak of trapezoidal inflow hydrograph at each junction
  coordScale: number;  // multiplier for all node coordinates
  progressiveSizing: boolean; // scale conduit diameter with upstream node count
  maxDiameterMultiplier: number; // upper bound on progressive diameter growth
  // Trapezoidal inflow shape as fractions of endTimeSec.

  // rise + plateau + fall should sum to ≤ 1.0.
  trapRiseFrac: number;
  trapPlateauFrac: number;
  trapFallFrac: number;
}

export type TrapezoidPresetKey =
  | "symmetric"
  | "storm-burst"
  | "slow-build"
  | "flash-flood"
  | "long-plateau"
  | "custom";

export interface TrapezoidPreset {
  key: TrapezoidPresetKey;
  label: string;
  description: string;
  rise: number;
  plateau: number;
  fall: number;
}

export const TRAPEZOID_PRESETS: TrapezoidPreset[] = [
  { key: "symmetric",    label: "Symmetric",       description: "25% rise · 50% plateau · 25% fall", rise: 0.25, plateau: 0.5,  fall: 0.25 },
  { key: "storm-burst",  label: "Storm burst",     description: "10% rise · 20% plateau · 70% fall", rise: 0.10, plateau: 0.2,  fall: 0.70 },
  { key: "slow-build",   label: "Slow build",      description: "40% rise · 20% plateau · 40% fall", rise: 0.40, plateau: 0.2,  fall: 0.40 },
  { key: "flash-flood",  label: "Flash flood",     description: "5% rise · 10% plateau · 85% fall",  rise: 0.05, plateau: 0.10, fall: 0.85 },
  { key: "long-plateau", label: "Long plateau",    description: "10% rise · 80% plateau · 10% fall", rise: 0.10, plateau: 0.80, fall: 0.10 },
];

export function detectTrapezoidPreset(opts: Pick<InpOptions, "trapRiseFrac" | "trapPlateauFrac" | "trapFallFrac">): TrapezoidPresetKey {
  for (const p of TRAPEZOID_PRESETS) {
    if (
      Math.abs(p.rise - opts.trapRiseFrac) < 1e-3 &&
      Math.abs(p.plateau - opts.trapPlateauFrac) < 1e-3 &&
      Math.abs(p.fall - opts.trapFallFrac) < 1e-3
    ) return p.key;
  }
  return "custom";
}

export const defaultOptions: InpOptions = {
  maxSeed: 100,
  flowUnits: "CFS",
  baseInvert: 0,
  invertDrop: 1,
  maxDepth: 10,
  conduitLength: 400,
  roughness: 0.013,
  diameter: 1.0,
  layoutMode: "symmetric",
  dwfBaseflow: 0,
  dwfPattern: "",
  endTimeSec: 43200, // 12 hours
  peakInflow: 1.0,
  coordScale: 0.05,
  progressiveSizing: false,
  maxDiameterMultiplier: 6,
  trapRiseFrac: 0.25,

  trapPlateauFrac: 0.5,
  trapFallFrac: 0.25,
};


function secsToHMS(s: number): string {
  const sec = Math.max(0, Math.floor(s));
  const h = Math.floor(sec / 3600);
  const m = Math.floor((sec % 3600) / 60);
  const ss = sec % 60;
  const p = (n: number) => String(n).padStart(2, "0");
  return `${p(h)}:${p(m)}:${p(ss)}`;
}

export interface BuildResult {
  inp: string;
  nodeCount: number;
  conduitCount: number;
  tree: CollatzTree;
  coords: Map<number, [number, number]>;
  inverts: Map<number, number>;
  endTimeSec: number;
  /** Upstream contributing node count per node (inclusive of the node itself). */
  upstreamCount: Map<number, number>;
  /** Diameter assigned to each conduit id (e.g. "C1", "C2", ...). */
  conduitDiameter: Map<string, number>;
}


const pad = (s: string | number, w: number) => String(s).padEnd(w);

export function buildInp(opts: InpOptions): BuildResult {
  const tree = buildTree(opts.maxSeed);
  const rawCoords = layoutFor(tree, opts.layoutMode);
  const coords = new Map<number, [number, number]>();
  for (const [n, [x, y]] of rawCoords) {
    coords.set(n, [x * opts.coordScale, y * opts.coordScale]);
  }

  const lines: string[] = [];
  const push = (s = "") => lines.push(s);

  push("[TITLE]");
  push(`Collatz Holy Tree SWMM5 network (seeds 1..${opts.maxSeed})`);
  push("Generated by Collatz SWMM5 INP Generator");
  push();

  push("[OPTIONS]");
  push(`FLOW_UNITS           ${opts.flowUnits}`);
  push("INFILTRATION         HORTON");
  push("FLOW_ROUTING         DYNWAVE");
  push("LINK_OFFSETS         DEPTH");
  push("MIN_SLOPE            0");
  push("ALLOW_PONDING        NO");
  push("SKIP_STEADY_STATE    NO");
  push("START_DATE           01/01/2024");
  push("START_TIME           00:00:00");
  push("REPORT_START_DATE    01/01/2024");
  push("REPORT_START_TIME    00:00:00");
  push("END_DATE             01/01/2024");
  push(`END_TIME             ${secsToHMS(opts.endTimeSec)}`);
  push("SWEEP_START          01/01");
  push("SWEEP_END            12/31");
  push("DRY_DAYS             0");
  push("REPORT_STEP          00:05:00");
  push("WET_STEP             00:05:00");
  push("DRY_STEP             01:00:00");
  push("ROUTING_STEP         0:00:10");
  push("LENGTHENING_STEP     5");
  push("INERTIAL_DAMPING     PARTIAL");
  push("NORMAL_FLOW_LIMITED  BOTH");
  push("VARIABLE_STEP        0.75");
  push("MIN_SURFAREA         12.566");

  push("[EVAPORATION]");
  push("CONSTANT  0.0");
  push("DRY_ONLY  NO");
  push();

  // invert for a node: deeper-in-tree (further from 1) = higher elevation
  const invertOf = (n: number) =>
    opts.baseInvert + (tree.depth.get(n) ?? 0) * opts.invertDrop;

  push("[JUNCTIONS]");
  push(";;Name           Elevation  MaxDepth   InitDepth  SurDepth   Aponded");
  for (const n of tree.nodes) {
    if (n === 1) continue;
    push(
      `${pad(n, 17)}${pad(invertOf(n).toFixed(3), 11)}${pad(
        opts.maxDepth,
        11,
      )}${pad(0, 11)}${pad(0, 11)}0`,
    );
  }
  push();

  push("[OUTFALLS]");
  push(";;Name           Elevation  Type       Stage Data        Gated");
  push(`${pad(1, 17)}${pad(opts.baseInvert.toFixed(3), 11)}FREE                            NO`);
  push();

  // Compute upstream contributing node count (each node contributes itself + all upstream).
  const children = new Map<number, number[]>();
  for (const [from, to] of tree.edges) {
    if (!children.has(to)) children.set(to, []);
    children.get(to)!.push(from);
  }
  const upstreamCount = new Map<number, number>();
  const countUp = (n: number): number => {
    if (upstreamCount.has(n)) return upstreamCount.get(n)!;
    let c = 1;
    for (const ch of children.get(n) ?? []) c += countUp(ch);
    upstreamCount.set(n, c);
    return c;
  };
  for (const n of tree.nodes) countUp(n);

  push("[CONDUITS]");
  push(";;Name           From Node        To Node          Length     Roughness  InOffset   OutOffset  InitFlow   MaxFlow");
  const edgeList = Array.from(tree.edges);
  let cid = 0;
  for (const [from, to] of edgeList) {
    cid++;
    push(
      `${pad("C" + cid, 17)}${pad(from, 17)}${pad(to, 17)}${pad(
        opts.conduitLength,
        11,
      )}${pad(opts.roughness, 11)}${pad(0, 11)}${pad(0, 11)}${pad(0, 11)}0`,
    );
  }
  push();

  // Progressive sizing: diameter grows with sqrt of upstream node count on the
  // upstream end of each conduit, capped at maxDiameterMultiplier × base.
  const totalUp = upstreamCount.get(1) ?? 1;
  const conduitDiameter = new Map<string, number>();
  const diameterFor = (fromNode: number): number => {
    if (!opts.progressiveSizing) return opts.diameter;
    const up = upstreamCount.get(fromNode) ?? 1;
    const scale = Math.min(opts.maxDiameterMultiplier, Math.sqrt(up));
    return opts.diameter * Math.max(1, scale);
  };
  void totalUp;

  push("[XSECTIONS]");
  push(";;Link           Shape        Geom1            Geom2      Geom3      Geom4      Barrels");
  for (let i = 0; i < edgeList.length; i++) {
    const [from] = edgeList[i];
    const dia = diameterFor(from);
    const id = "C" + (i + 1);
    conduitDiameter.set(id, dia);
    push(
      `${pad(id, 17)}${pad("CIRCULAR", 13)}${pad(
        dia.toFixed(3),
        17,
      )}${pad(0, 11)}${pad(0, 11)}${pad(0, 11)}1`,
    );
  }
  push();


  push("[DWF]");
  push(";;Node           Constituent      Baseline   Patterns");
  for (const n of tree.nodes) {
    if (n === 1) continue;
    const pat = opts.dwfPattern.trim();
    push(
      `${pad(n, 17)}${pad("FLOW", 17)}${pad(
        opts.dwfBaseflow.toFixed(4),
        11,
      )}${pat ? `"${pat}"` : ""}`,
    );
  }
  push();

  // Trapezoidal inflow hydrograph applied at every junction
  // Breakpoints: (0,0) ramp up to peak at t/4, plateau to 3t/4, ramp down to t.
  const tsName = "TRAPZ";
  const endH = opts.endTimeSec / 3600;
  const peak = opts.peakInflow;
  const fmtH = (h: number) => {
    const total = Math.max(0, Math.round(h * 3600));
    const hh = Math.floor(total / 3600);
    const mm = Math.floor((total % 3600) / 60);
    const ss = total % 60;
    const p = (n: number) => String(n).padStart(2, "0");
    return `${p(hh)}:${p(mm)}:${p(ss)}`;
  };
  push("[INFLOWS]");
  push(";;Node           Constituent      Time Series      Type     Mfactor  Sfactor  Baseline Pattern");
  for (const n of tree.nodes) {
    if (n === 1) continue;
    push(
      `${pad(n, 17)}${pad("FLOW", 17)}${pad(tsName, 17)}${pad("FLOW", 9)}${pad(
        "1.0",
        9,
      )}${pad("1.0", 9)}`,
    );
  }
  push();

  push("[TIMESERIES]");
  push(";;Name           Date       Time       Value");
  const rise = Math.max(0, opts.trapRiseFrac) * endH;
  const plateau = Math.max(0, opts.trapPlateauFrac) * endH;
  const fall = Math.max(0, opts.trapFallFrac) * endH;
  const tsRows: Array<[string, number]> = [
    [fmtH(0), 0],
    [fmtH(rise), peak],
    [fmtH(rise + plateau), peak],
    [fmtH(rise + plateau + fall), 0],
  ];
  // If the shape ends before end-of-sim, hold zero at the end so SWMM has a bracket.
  if (rise + plateau + fall < endH - 1e-6) {
    tsRows.push([fmtH(endH), 0]);
  }
  for (const [t, v] of tsRows) {
    push(`${pad(tsName, 17)}${pad(t, 11)}${v.toFixed(4)}`);
  }
  push();


  push("[REPORT]");
  push("INPUT      NO");
  push("CONTROLS   NO");
  push("SUBCATCHMENTS ALL");
  push("NODES ALL");
  push("LINKS ALL");
  push();

  push("[COORDINATES]");
  push(";;Node           X-Coord            Y-Coord");
  for (const n of tree.nodes) {
    const [x, y] = coords.get(n) ?? [0, 0];
    push(`${pad(n, 17)}${pad(x.toFixed(3), 19)}${y.toFixed(3)}`);
  }
  push();

  push("[VERTICES]");
  push(";;Link           X-Coord            Y-Coord");
  push();

  const inverts = new Map<number, number>();
  for (const n of tree.nodes) inverts.set(n, invertOf(n));

  return {
    inp: lines.join("\n"),
    nodeCount: tree.nodes.size,
    conduitCount: cid,
    tree,
    coords,
    inverts,
    endTimeSec: opts.endTimeSec,
    upstreamCount,
    conduitDiameter,
  };
}


