import { buildTree, type CollatzTree } from "../collatz";
import { layoutFor, type LayoutMode } from "./layout";

export interface InpOptions {
  maxSeed: number;
  flowUnits: "CFS" | "LPS" | "CMS";
  baseInvert: number;
  invertDrop: number; // per depth step toward outfall
  maxDepth: number;
  conduitLength: number;
  roughness: number;
  diameter: number;
  layoutMode: LayoutMode;
  dwfBaseflow: number; // user-defined DWF average flow at each junction
  dwfPattern: string;  // optional pattern name ("" = none)
  endTimeSec: number;  // simulation duration in seconds
}

export const defaultOptions: InpOptions = {
  maxSeed: 100,
  flowUnits: "CFS",
  baseInvert: 0,
  invertDrop: 1,
  maxDepth: 10,
  conduitLength: 400,
  roughness: 0.013,
  diameter: 1.0,
  layoutMode: "symmetric",
  dwfBaseflow: 0.1,
  dwfPattern: "",
  endTimeSec: 21600, // 6 hours
};

function secsToHMS(s: number): string {
  const sec = Math.max(0, Math.floor(s));
  const h = Math.floor(sec / 3600);
  const m = Math.floor((sec % 3600) / 60);
  const ss = sec % 60;
  const p = (n: number) => String(n).padStart(2, "0");
  return `${p(h)}:${p(m)}:${p(ss)}`;
}

export interface BuildResult {
  inp: string;
  nodeCount: number;
  conduitCount: number;
  tree: CollatzTree;
  coords: Map<number, [number, number]>;
  inverts: Map<number, number>;
}

const pad = (s: string | number, w: number) => String(s).padEnd(w);

export function buildInp(opts: InpOptions): BuildResult {
  const tree = buildTree(opts.maxSeed);
  const coords = layoutFor(tree, opts.layoutMode);

  const lines: string[] = [];
  const push = (s = "") => lines.push(s);

  push("[TITLE]");
  push(`Collatz Holy Tree SWMM5 network (seeds 1..${opts.maxSeed})`);
  push("Generated by Collatz SWMM5 INP Generator");
  push();

  push("[OPTIONS]");
  push(`FLOW_UNITS           ${opts.flowUnits}`);
  push("INFILTRATION         HORTON");
  push("FLOW_ROUTING         DYNWAVE");
  push("LINK_OFFSETS         DEPTH");
  push("MIN_SLOPE            0");
  push("ALLOW_PONDING        NO");
  push("SKIP_STEADY_STATE    NO");
  push("START_DATE           01/01/2024");
  push("START_TIME           00:00:00");
  push("REPORT_START_DATE    01/01/2024");
  push("REPORT_START_TIME    00:00:00");
  push("END_DATE             01/01/2024");
  push(`END_TIME             ${secsToHMS(opts.endTimeSec)}`);
  push("SWEEP_START          01/01");
  push("SWEEP_END            12/31");
  push("DRY_DAYS             0");
  push("REPORT_STEP          00:05:00");
  push("WET_STEP             00:05:00");
  push("DRY_STEP             01:00:00");
  push("ROUTING_STEP         0:00:10");
  push("LENGTHENING_STEP     5");
  push("INERTIAL_DAMPING     PARTIAL");
  push("NORMAL_FLOW_LIMITED  BOTH");
  push("VARIABLE_STEP        0.75");
  push("MIN_SURFAREA         12.566");

  push("[EVAPORATION]");
  push("CONSTANT  0.0");
  push("DRY_ONLY  NO");
  push();

  // invert for a node: deeper-in-tree (further from 1) = higher elevation
  const invertOf = (n: number) =>
    opts.baseInvert + (tree.depth.get(n) ?? 0) * opts.invertDrop;

  push("[JUNCTIONS]");
  push(";;Name           Elevation  MaxDepth   InitDepth  SurDepth   Aponded");
  for (const n of tree.nodes) {
    if (n === 1) continue;
    push(
      `${pad(n, 17)}${pad(invertOf(n).toFixed(3), 11)}${pad(
        opts.maxDepth,
        11,
      )}${pad(0, 11)}${pad(0, 11)}0`,
    );
  }
  push();

  push("[OUTFALLS]");
  push(";;Name           Elevation  Type       Stage Data        Gated");
  push(`${pad(1, 17)}${pad(opts.baseInvert.toFixed(3), 11)}FREE                            NO`);
  push();

  push("[CONDUITS]");
  push(";;Name           From Node        To Node          Length     Roughness  InOffset   OutOffset  InitFlow   MaxFlow");
  let cid = 0;
  for (const [from, to] of tree.edges) {
    cid++;
    push(
      `${pad("C" + cid, 17)}${pad(from, 17)}${pad(to, 17)}${pad(
        opts.conduitLength,
        11,
      )}${pad(opts.roughness, 11)}${pad(0, 11)}${pad(0, 11)}${pad(0, 11)}0`,
    );
  }
  push();

  push("[XSECTIONS]");
  push(";;Link           Shape        Geom1            Geom2      Geom3      Geom4      Barrels");
  for (let i = 1; i <= cid; i++) {
    push(
      `${pad("C" + i, 17)}${pad("CIRCULAR", 13)}${pad(
        opts.diameter.toFixed(3),
        17,
      )}${pad(0, 11)}${pad(0, 11)}${pad(0, 11)}1`,
    );
  }
  push();

  push("[DWF]");
  push(";;Node           Constituent      Baseline   Patterns");
  for (const n of tree.nodes) {
    if (n === 1) continue;
    const pat = opts.dwfPattern.trim();
    push(
      `${pad(n, 17)}${pad("FLOW", 17)}${pad(
        opts.dwfBaseflow.toFixed(4),
        11,
      )}${pat ? `"${pat}"` : ""}`,
    );
  }
  push();

  push("[REPORT]");
  push("INPUT      NO");
  push("CONTROLS   NO");
  push("SUBCATCHMENTS ALL");
  push("NODES ALL");
  push("LINKS ALL");
  push();

  push("[COORDINATES]");
  push(";;Node           X-Coord            Y-Coord");
  for (const n of tree.nodes) {
    const [x, y] = coords.get(n) ?? [0, 0];
    push(`${pad(n, 17)}${pad(x.toFixed(3), 19)}${y.toFixed(3)}`);
  }
  push();

  push("[VERTICES]");
  push(";;Link           X-Coord            Y-Coord");
  push();

  const inverts = new Map<number, number>();
  for (const n of tree.nodes) inverts.set(n, invertOf(n));

  return {
    inp: lines.join("\n"),
    nodeCount: tree.nodes.size,
    conduitCount: cid,
    tree,
    coords,
    inverts,
  };
}
