/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GithubSyncRouteImport } from './routes/github-sync'
import { Route as IndexRouteImport } from './routes/index'

const GithubSyncRoute = GithubSyncRouteImport.update({
  id: '/github-sync',
  path: '/github-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/github-sync': typeof GithubSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/github-sync': typeof GithubSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/github-sync': typeof GithubSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/github-sync'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/github-sync'
  id: '__root__' | '/' | '/github-sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GithubSyncRoute: typeof GithubSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/github-sync': {
      id: '/github-sync'
      path: '/github-sync'
      fullPath: '/github-sync'
      preLoaderRoute: typeof GithubSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GithubSyncRoute: GithubSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
